### ISSUE TITLE
Input settings anti-pattern

### ISSUE THREAD

**Issue by Tomires** [turbobutton/tbutt-vr#1]
Hello,

would it be possible to change checkbox labels in the Input Settings dialogue to say 'Enabled' independently on the state of the checkbox? I have been wondering for solid 20 minutes why input does not work in my project thinking that all input options are enabled by default. 😄 

![capture](https://user-images.githubusercontent.com/7209990/50478946-32b5c200-09d4-11e9-8905-b28fb10a9bb7.PNG)

**Comment by hlink** [comment]
Ahhh, I understand why this was confusing. I was trying to keep the same general language as the Core Settings screen (where it says enabled or disabled) but that doesn't make sense with the checkbox design.

Updating it to maintain color coding but act as a call to action instead:
![image](https://user-images.githubusercontent.com/3581594/50607453-186d5f80-0e7e-11e9-9526-1398cdf41ef4.png)
