### ISSUE TITLE
TBAudioListener gets destroyed on scene load when TBCameraRig is set to DontDestroyOnLoad

### ISSUE THREAD

**Issue by ryangreen** [turbobutton/tbutt-vr#10]
**Describe the bug**
I'm using Zenject IOC for a project which preserves objects it creates in the ProjectContext as DontDestroyOnLoad. In my case this includes the TBCameraRig.  

**To Reproduce**
Load a new scene with your TBCameraRig set to DontDestroyOnLoad and the TBAudioListener gets destroyed

**Expected behavior**
TBAudioListener is preserved

**Screenshots**

**Additional information:**
 - Unity 2019.1.5
 - Oculus
 - TButt 1.1.0

**Additional context**

**Comment by hlink** [comment]
This should be fixed on the beta branch (v1.2.0). TBCameraRig now checks to see if there is a TBAudioListener every time a new scene is loaded and creates one if necessary.
