### ISSUE TITLE
TBInput.GetFinger(TBInput.Finger.Thumb) ignores Oculus Thumb Rest

### ISSUE THREAD

**Issue by russellweed** [turbobutton/tbutt-vr#5]
**Describe the bug**
It appears that the API `TBInput.GetFinger(TBInput.Finger.Thumb)` does not track the Thumb Rest capacitive area on the CV1 Oculus Touch controllers. These controls are `Touch.PrimaryThumbRest`/`Touch.SecondaryThumbRest` [in the Unity manual](https://docs.unity3d.com/Manual/OculusControllers.html).

**To Reproduce**
Open the InputTest demo scene, start the demo, and touch the Thumb Rest capacitive area. No change will be registered in the input levels of the FingerInputPanel.

**Expected behavior**
When the user touches the Thumb Rest, the thumb should close down in the same way as when the user touches the thumbstick or face buttons.

**Additional information:**
 - Unity Version: 2018.3.13f1
 - Affected Integrations: Oculus
 - TButt Version: 1.0.2

**Additional context**
The Touch Rest buttons are seldomly used in most projects, and most probably will never miss them, so this is probably a low priority fix. In addition, the Thumb Rest has been removed from the remodeled Touch controllers included with the Rift S and Quest.

**Comment by hlink** [comment]
This functionality is now available on the beta branch, and will be in the full 1.2.0 release.
